name: Prepare Release

on:
  push:
    branches:
      - trunk

jobs:
  bump-version:
    name: Bump Version on trunk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Automated Version Bump
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_USER: ${{ secrets.ACTION_USER }}
          GITHUB_EMAIL: ${{ secrets.ACTION_EMAIL }}
        with:
          minor-wording: "add,Adds,new"
          major-wording: "MAJOR,cut-major,Major,major,breaking change"
          patch-wording: "fixes,fix,patch,patches"
          default: minor
          bump-policy: "all"
          commit-message: "CI: bumps version to {{version}} [skip ci]"

      - name: Version Bump Output
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: ${{steps.github_release.outputs.changelog}}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          title: "Release ${{ steps.version-bump.outputs.newTag }}"
          body: |
            This PR is auto-generated
            for release ${{ steps.version-bump.outputs.newTag }}.
          labels: automated-pr
          branch: trunk
